In [1]:
require 'nn';
require 'optim'

In [77]:
function computeKappa (mat)
    local N = mat:size(1)
    local tmp = torch.range(1, N):view(1, N)
    local tmp1 = torch.range(1, N):view(N, 1)
    local W= tmp:expandAs(mat)-tmp1:expandAs(mat)
    W:cmul(W)
    W:div((N-1)*(N-1))
    local total = mat:sum()
    local row_sum = mat:sum(1)/total
    local col_sum = mat:sum(2)
    local E = torch.cmul(row_sum:expandAs(mat), col_sum:expandAs(mat))
    local kappa = 1 - torch.cmul(W, mat):sum()/torch.cmul(W, E):sum()
    return kappa
end

In [70]:
mat = mat:double()

In [72]:
total = mat:sum()
print("total", total)
row_sum = mat:sum(1)/total
print("row_sum", row_sum)
col_sum = mat:sum(2)
print("col_sum", col_sum)

total	100	
row_sum	 0.6000  0.3000  0.1000
[torch.DoubleTensor of size 1x3]

col_sum	 50
 30
 20
[torch.DoubleTensor of size 3x1]



In [73]:
torch.cmul(row_sum:expandAs(mat), col_sum:expandAs(mat))

 30  15   5
 18   9   3
 12   6   2
[torch.DoubleTensor of size 3x3]



In [69]:
row_sum:double()/total

 0.6000  0.3000  0.1000
[torch.DoubleTensor of size 1x3]



In [24]:
confusion = optim.ConfusionMatrix({1,2,3})

In [25]:
confusion.mat

 0  0  0
 0  0  0
 0  0  0
[torch.LongTensor of size 3x3]



In [30]:
confusion.mat[1][1] = 44
confusion.mat[1][2] = 5
confusion.mat[1][3] = 1

confusion.mat[2][1] = 7
confusion.mat[2][2] = 20
confusion.mat[2][3] = 3

confusion.mat[3][1] = 9
confusion.mat[3][2] = 5
confusion.mat[3][3] = 6

In [31]:
confusion

ConfusionMatrix:
[[      44       5       1]   88.000% 	[class: 1]
 [       7      20       3]   66.667% 	[class: 2]
 [       9       5       6]]  30.000% 	[class: 3]
 + average row correct: 61.555556456248% 
 + average rowUcol correct (VOC measure): 47.222222884496% 
 + global correct: 70%
{
  _mat_flat : LongTensor - size: 9
  valids : FloatTensor - size: 3
  mat : LongTensor - size: 3x3
  averageUnionValid : 0.47222222884496
  _targ_idx : LongTensor - empty
  averageValid : 0.61555556456248
  classes : 
    {
      1 : 1
      2 : 2
      3 : 3
    }
  _prediction : FloatTensor - empty
  _pred_idx : LongTensor - empty
  nclasses : 3
  _max : FloatTensor - empty
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 3
  totalValid : 0.7
}


In [74]:
mat = confusion.mat:double()

In [37]:
N = mat:size(1)
tmp = torch.range(1, N):view(1, N)
tmp1 = torch.range(1, N):view(N, 1)

In [47]:
weightMatrix = 1- torch.pow(tmp:expandAs(mat)-tmp1:expandAs(mat), 2)/((N-1)^2)

In [48]:
weightMatrix

 1.0000  0.7500  0.0000
 0.7500  1.0000  0.7500
 0.0000  0.7500  1.0000
[torch.DoubleTensor of size 3x3]



In [78]:
computeKappa(mat)

0.45454545454545	
