In [4]:
require 'nn';
require 'optim'

In [3]:
classes = {1, 2, 3, 4, 5}
N = 10
target = torch.Tensor(N):uniform(1,5):round()
output = torch.Tensor(N):uniform(1,5):round()

In [5]:
confusion = optim.ConfusionMatrix(classes)

In [13]:
for i = 1, 10 do
    confusion:add(output[i], target[i])
end

In [14]:
confusion

ConfusionMatrix:
[[       0       1       0       2       0]   0.000% 	[class: 1]
 [       0       1       0       2       0]   33.333% 	[class: 2]
 [       1       0       0       1       0]   0.000% 	[class: 3]
 [       1       0       0       2       0]   66.667% 	[class: 4]
 [       0       0       0       1       0]]  0.000% 	[class: 5]
 + average row correct: 20.000000596046% 
 + average rowUcol correct (VOC measure): 9.4444444775581% 
 + global correct: 25%
{
  _mat_flat : LongTensor - size: 25
  valids : FloatTensor - size: 5
  mat : LongTensor - size: 5x5
  averageUnionValid : 0.094444444775581
  _targ_idx : LongTensor - size: 1
  averageValid : 0.20000000596046
  classes : 
    {
      1 : 1
      2 : 2
      3 : 3
      4 : 4
      5 : 5
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 5
  _max : FloatTensor - size: 1
  _target : FloatTensor - size: 10
  unionvalids : FloatTensor - size: 5


  totalValid : 0.25
}


In [19]:
ii=torch.exp(torch.abs(torch.randn(10, 2)))

In [20]:
ii

  3.0396   5.3191
  1.3552   4.1154
  1.2418   2.1556
 11.5497   5.2614
  1.2343   2.2378
  1.1226   1.1156
  1.4990   1.0661
  1.2156   2.1764
  1.5781   2.2484
  6.6188   1.0337
[torch.DoubleTensor of size 10x2]



In [25]:
m = nn.Max(2)

In [28]:
a, b = m:forward(ii)

In [29]:
a

  5.3191
  4.1154
  2.1556
 11.5497
  2.2378
  1.1226
  1.4990
  2.1764
  2.2484
  6.6188
[torch.DoubleTensor of size 10]

