In [4]:
require 'nn';
require 'optim'

In [55]:
classes = {1, 2, 3, 4, 5}
N = 10
target = torch.Tensor(N):uniform(1,5):round()
predictions = torch.Tensor(N):uniform(1,5):round()

In [56]:
confusion = optim.ConfusionMatrix(classes)
print(torch.cat(predictions:reshape(N, 1), target:reshape(N,1), 2))

 2  4
 3  2
 3  2
 4  5
 3  4
 3  2
 5  2
 5  2
 4  4
 4  2
[torch.DoubleTensor of size 10x2]



In [57]:
confusion:batchAdd(predictions, target)

In [58]:
confusion

ConfusionMatrix:
[[       0       0       0       0       0]   nan% 	[class: 1]
 [       0       0       3       1       2]   0.000% 	[class: 2]
 [       0       0       0       0       0]   nan% 	[class: 3]
 [       0       1       1       1       0]   33.333% 	[class: 4]
 [       0       0       0       1       0]]  0.000% 	[class: 5]
 + average row correct: 11.111111442248% 
 + average rowUcol correct (VOC measure): 6.6666667660077% 
 + global correct: 10%
{
  _mat_flat : LongTensor - size: 25
  valids : FloatTensor - size: 5
  mat : LongTensor - size: 5x5
  averageUnionValid : 0.066666667660077
  _targ_idx : LongTensor - empty
  averageValid : 0.11111111442248
  classes : 
    {
      1 : 1
      2 : 2
      3 : 3
      4 : 4
      5 : 5
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - empty
  nclasses : 5
  _max : FloatTensor - empty
  _target : FloatTensor - size: 10
  unionvalids : FloatTensor - size: 5
  totalValid : 0.1
}


In [19]:
ii=torch.exp(torch.abs(torch.randn(10, 2)))

In [20]:
ii

  3.0396   5.3191
  1.3552   4.1154
  1.2418   2.1556
 11.5497   5.2614
  1.2343   2.2378
  1.1226   1.1156
  1.4990   1.0661
  1.2156   2.1764
  1.5781   2.2484
  6.6188   1.0337
[torch.DoubleTensor of size 10x2]



In [25]:
m = nn.Max(2)

In [28]:
a, b = m:forward(ii)

In [29]:
a

  5.3191
  4.1154
  2.1556
 11.5497
  2.2378
  1.1226
  1.4990
  2.1764
  2.2484
  6.6188
[torch.DoubleTensor of size 10]

